In [1]:
import pandas as pd
import numpy as np

In [4]:
np.random.seed(42) 
table = pd.DataFrame()
table['Date'] = pd.date_range(start='2024-02-15', end='2025-06-30', freq='D')

table['ID_Customer'] = np.random.randint(10, 300, size=len(table))

products = [
    'Pistacho_cookie',
    'Redvelvet_cookie',
    'Chesscakelemon_cookie',
    'Biscoft_cookie',
    'Choconutella_cookie',
    'Chocomix_cookie',
    'Mini_cookies'
]

table['Product'] = np.random.choice(products, size=len(table))

product_prices = {
    'Pistacho_cookie': 5.5,
    'Redvelvet_cookie': 5.0,
    'Chesscakelemon_cookie': 5.5,
    'Biscoft_cookie': 4.5,
    'Choconutella_cookie': 4.0,
    'Chocomix_cookie': 4.0,
    'Mini_cookies': 2.0
}

product_costs = {
    'Pistacho_cookie': 2.5,
    'Redvelvet_cookie': 2.2,
    'Chesscakelemon_cookie': 2.6,
    'Biscoft_cookie': 2.0,
    'Choconutella_cookie': 1.8,
    'Chocomix_cookie': 1.9,
    'Mini_cookies': 3.8
}

table['price_per_unit'] = table['Product'].map(product_prices) 

table['cost_per_unit'] = table['Product'].map(product_costs)

table['profit_per_unit'] = table['price_per_unit'] - table['cost_per_unit']

table['Units_sold'] = np.random.randint(4, 12, size=len(table))

table['Total_sell'] = table['Units_sold'] * table['price_per_unit']

table['Total_cost'] = table['Units_sold'] * table['cost_per_unit']

table['Total_profit'] = table['Total_sell'] - table['Total_cost']

table

,Date,ID_Customer,Product,price_per_unit,cost_per_unit,profit_per_unit,Units_sold,Total_sell,Total_cost,Total_profit
0,2024-02-15,112,Redvelvet_cookie,5.0,2.2,2.8,5,25.0,11.0,14.0
1,2024-02-16,280,Redvelvet_cookie,5.0,2.2,2.8,9,45.0,19.8,25.2
2,2024-02-17,116,Choconutella_cookie,4.0,1.8,2.2,8,32.0,14.4,17.6
3,2024-02-18,81,Choconutella_cookie,4.0,1.8,2.2,11,44.0,19.8,24.2
4,2024-02-19,198,Choconutella_cookie,4.0,1.8,2.2,6,24.0,10.8,13.2
...,...,...,...,...,...,...,...,...,...,...
497,2025-06-26,183,Pistacho_cookie,5.5,2.5,3.0,4,22.0,10.0,12.0
498,2025-06-27,150,Choconutella_cookie,4.0,1.8,2.2,6,24.0,10.8,13.2
499,2025-06-28,177,Chocomix_cookie,4.0,1.9,2.1,10,40.0,19.0,21.0
500,2025-06-29,179,Biscoft_cookie,4.5,2.0,2.5,11,49.5,22.0,27.5
501,2025-06-30,292,Biscoft_cookie,4.5,2.0,2.5,6,27.0,12.0,15.0

In [ ]:
table = table.sort_values(by="Date")

table['Customer_type'] = table.duplicated(subset='ID_Customer', keep='first')\
                                .map({False: 'New', True: 'Returning'})

In [ ]:
table

,Date,ID_Customer,Product,price_per_unit,cost_per_unit,profit_per_unit,Units_sold,Total_sell,Total_cost,Total_profit,Customer_type
0,2024-02-15,112,Redvelvet_cookie,5.0,2.2,2.8,5,25.0,11.0,14.0,New
1,2024-02-16,280,Redvelvet_cookie,5.0,2.2,2.8,9,45.0,19.8,25.2,New
2,2024-02-17,116,Choconutella_cookie,4.0,1.8,2.2,8,32.0,14.4,17.6,New
3,2024-02-18,81,Choconutella_cookie,4.0,1.8,2.2,11,44.0,19.8,24.2,New
4,2024-02-19,198,Choconutella_cookie,4.0,1.8,2.2,6,24.0,10.8,13.2,New
...,...,...,...,...,...,...,...,...,...,...,...
497,2025-06-26,183,Pistacho_cookie,5.5,2.5,3.0,4,22.0,10.0,12.0,Returning
498,2025-06-27,150,Choconutella_cookie,4.0,1.8,2.2,6,24.0,10.8,13.2,New
499,2025-06-28,177,Chocomix_cookie,4.0,1.9,2.1,10,40.0,19.0,21.0,Returning
500,2025-06-29,179,Biscoft_cookie,4.5,2.0,2.5,11,49.5,22.0,27.5,Returning
501,2025-06-30,292,Biscoft_cookie,4.5,2.0,2.5,6,27.0,12.0,15.0,Returning

In [20]:
dates = pd.date_range(start='2024-02-15', end='2025-06-30', freq='M')

# Simulate Month operational costs
costs = pd.DataFrame({
    'Date': dates,
    'flour': np.random.uniform(10, 15, len(dates)),
    'butter': np.random.uniform(8, 12, len(dates)),
    'sugar': np.random.uniform(6, 10, len(dates)),
    'cream_cheese': np.random.uniform(0, 8, len(dates)),
    'lemon': np.random.uniform(1.5, 2.5, len(dates)),
    'coconut_scraper': np.random.uniform(0, 3, len(dates)),
    'cream_nutella': np.random.uniform(0, 10, len(dates)),
    'cream_pistacho': np.random.uniform(0, 15, len(dates)),
    'electricity': np.random.uniform(5, 9, len(dates)),
    'paper_trays': np.random.uniform(0, 3.5, len(dates)),
    'cookie_box': np.random.uniform(0, 30, len(dates)),
    'water': np.random.uniform(8, 15, len(dates)),
    'dish_soap': np.random.uniform(0, 2.5, len(dates)),
    'publicity': np.random.uniform(0, 15, len(dates)),
})

# Total cost per day
costs['total_month_cost'] = costs.drop(columns=['Date']).sum(axis=1)

# Preview
print(costs.head())

        Date      flour     butter     sugar  cream_cheese     lemon  \
0 2024-02-29  10.271356   8.121357  8.856862      7.921406  2.145511
1 2024-03-31  12.983153  11.994393  6.278035      0.606812  1.896356
2 2024-04-30  10.434315  10.494511  9.888666      5.294326  1.577839
3 2024-05-31  13.508568  10.234828  6.057108      3.585824  1.873635
4 2024-06-30  10.263211   8.238050  8.405267      3.572815  2.188768

   coconut_scraper  cream_nutella  cream_pistacho  electricity  paper_trays  \
0         0.507996       0.616419       14.683945     5.637561     2.935440
1         2.495970       9.585456        2.585857     5.176369     2.037633
2         1.715545       1.419332        5.362247     6.575950     0.870857
3         1.751669       3.047228       10.941391     6.665569     2.314317
4         0.629326       8.225178       14.459156     6.803629     2.484668

   cookie_box      water  dish_soap  publicity  total_month_cost
0    7.568073   9.073073   1.010550  14.917886         94.267435
1    4.699421  14.403263   1.123707  14.348563         90.214988
2   28.587309   8.450836   2.429811  12.652188        105.753732
3   12.162119   8.385264   2.125668  10.325608         92.978797
4   10.116597   9.311453   1.765922   4.422984         90.887024

/tmp/ipykernel_2643/850671486.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range(start='2024-02-15', end='2025-06-30', freq='M')